services:
  apps1:
    build: .
    image: java:latest
    container_name: java1
    ports:
      - 8080:8080
    networks:
      - my-net

  apps2:
    build: .
    image: java:latest
    container_name: java2
    ports:
      - 8083:8080
    networks:
      - my-net

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - my-net
    depends_on:
    - apps1
    - apps2

networks:
  my-net: