log_format upstreamlog '$remote_addr - $host → $upstream_addr '
                       '[$time_local] "$request" $status';

access_log /var/log/nginx/access.log upstreamlog;


upstream backend {
    server apps1:8080 weight=9;
    server apps2:8080 weight=1;
}

server{
    listen 80;

    location / {
        proxy_pass http://backend;
    }
}